USE Branden1137913;

CREATE TABLE USERS
(USERID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

USERNAME VARCHAR(200) NOT NULL,

PASSWORD VARCHAR(200) NOT NULL);

SELECT USERNAME, PASSWORD
FROM USERS;

DESC USERS;
